### ISSUE TITLE
Emulators?

### ISSUE THREAD

**Issue by ghost** [willemml/numworks_rust#16]
Android emulator?
Windows emulator?
Linux emulator?
iOS emulator?

This would be awesome to have because it would make it so that we could make rustworks work in a fully open source platform, like, for example, creating our own calculator hardware (fully open source unlike Numworks).

**Comment by RedGl0w** [comment]
@boricj started working on a port of qemu for numworks, and I've forked it and started myself too to continue the port. You can find it here : https://github.com/RedGl0w/numworks-qemu
That would probably be the better solution for emulating, even if there are still some big issues (how to integrate the keyboard ?, not yet a port of n0110, ...)

**Comment by RedGl0w** [comment]
> Project still seems alive, so, you got a star!

I started working on that a few days ago, hopefully it's still alive :p

**Comment by RedGl0w** [comment]
At the current state, nope
(because currently it almost runs well the n0100 model)
But it shouldn't be that hard to run the n0110

**Comment by RedGl0w** [comment]
> Do you have Matrix @RedGl0w ?

Only have it for the qemu bridge with their irc. I'm way more active on the omega discord

**Comment by willemml** [comment]
> Oh, and please, keep going with this project, it is the only attempt at making an open source calculator software. This is extremely valued for me, so, I will help you whenever I can.

I am glad to hear! It's one of my favourite projects, though unfortunately I have not had much time to look at it recently, and when I do I keep hitting the blocker of getting the external flash driver working correctly.



> Android emulator? Windows emulator? Linux emulator? iOS emulator?
> 
> This would be awesome to have because it would make it so that we could make rustworks work in a fully open source platform, like, for example, creating our own calculator hardware (fully open source unlike Numworks).

This is entirely possible. I have kept the "OS" code base as separate as possible from the board support / hardware driver crate, so theoretically it should be fairly easy to re-implement to work with a GUI and the system functions on a Desktop/Mobile OS.
I am also using the `embedded-graphics` crate which if I remember correctly provides a web emulator.

Of course if the qemu solution can be made to work that would be even better because it would allow for things like debugging and development by people who don't own a Numworks calculator. The only downside to it is making an iOS app.

**Comment by RedGl0w** [comment]
> Of course if the qemu solution can be made to work that would be even better because it would allow for things like debugging and development by people who don't own a Numworks calculator. The only downside to it is making an iOS app.

Qemu is very useful indeed (I can easily connect gdb to it and even debug what doesn't work yet on the emulator with it). That's super neat, and qemu already has already almost everything to port the numworks. However the port on mobile platform is something I've not thought yet at all

**Comment by RedGl0w** [comment]
Plop : there's a very minimal implementation of n0110 now on numworks_qemu branch. It currently emulates well the epsilon 15 firmware, but there's still some things to fix and change :p
